# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: developeriq-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: developeriq
  replicas: 4
  template:
    metadata:
      name: developeriq-tmpl
      labels:
        app: developeriq
    spec:
      containers:
        - name: developeriq
          image: developeriq:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000