# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: developeriq-svc
spec:
  type: LoadBalancer
  selector:
    app: developeriq
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
